### ISSUE TITLE
"ValueError: Input GeoDataFrame must contain only LineString features."

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/street-view-green-view#26]
can't get the `create_points` process to work with a different sample dataset. i can't find a difference that would lead to the failure.

the file: [jakarta_road_sample_small.zip](https://github.com/AmericanRedCross/street-view-green-view/files/14704150/jakarta_road_sample_small.zip)

the error message:
```
python -m src.create_points data/raw/jakarta_road_sample_small.zip data/interim/jakarta_road_sample_small.gpkg
Traceback (most recent call last):

  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "/Users/danbjoseph/GitHub/americanredcross/street-view-green-view/src/create_points.py", line 141, in <module>
    app()

  File "/Users/danbjoseph/GitHub/americanredcross/street-view-green-view/src/create_points.py", line 136, in main
    gdf = create_points(gdf, mini_dist=mini_dist)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/danbjoseph/GitHub/americanredcross/street-view-green-view/src/create_points.py", line 97, in create_points
    raise ValueError("Input GeoDataFrame must contain only LineString features.")

ValueError: Input GeoDataFrame must contain only LineString features.
```

### (not working) Jakarta sample details

<img width="765" alt="Screenshot 2024-03-21 at 12 18 04 PM" src="https://github.com/AmericanRedCross/street-view-green-view/assets/4806884/62e4cc58-fca9-44cf-b293-5f34b4d87520">
<img width="754" alt="Screenshot 2024-03-21 at 12 18 51 PM" src="https://github.com/AmericanRedCross/street-view-green-view/assets/4806884/74411350-16ea-4ae7-a7a3-5c05c5c32be8">

### (working) Three Rivers sample details

<img width="766" alt="Screenshot 2024-03-21 at 12 18 16 PM" src="https://github.com/AmericanRedCross/street-view-green-view/assets/4806884/0fbe2207-2288-400b-9f3b-9b308a78e55c">
<img width="760" alt="Screenshot 2024-03-21 at 12 18 35 PM" src="https://github.com/AmericanRedCross/street-view-green-view/assets/4806884/a1dde396-d301-433c-807e-92b05bc61086">

**Comment by ioalexei** [comment]
Quick look in geopandas suggests there are features with None as geom type, which seems weird but which I assume is what causes `create_points` to fail. 

```
>>> gpd.read_file("./jakarta_road_sample_small.zip")

          highway          osm_id                                           geometry
0        tertiary   way/155964624  LINESTRING (106.85513 -6.32937, 106.85518 -6.3...
1        tertiary   way/157974609                                               None
2     residential   way/157974611                                               None
3     residential   way/158979934                                               None
4     residential   way/158979937  LINESTRING (106.85874 -6.32874, 106.85866 -6.3...
..            ...             ...                                                ...
78  living_street  way/1228079958                                               None
79  living_street  way/1240606898  LINESTRING (106.85774 -6.32645, 106.85772 -6.3...
80  living_street  way/1240606900                                               None
81    residential  way/1245158482  LINESTRING (106.85653 -6.32900, 106.85631 -6.3...
82       tertiary  way/1259596877                                               None
```

Adding a geomtry type column in QGIS shows something similar: 
![image](https://github.com/AmericanRedCross/street-view-green-view/assets/3179403/73198edd-6a2a-4396-8623-7afbca897c67)

... and from an eyeball it doesn't look like QGIS is displaying 83 features:
![image](https://github.com/AmericanRedCross/street-view-green-view/assets/3179403/20df653c-ae23-4e6f-9f4d-2d1db142e6a7)

How did you generate the dataset?

Regardless, would be a good idea to add a check to `check_points` to check that `geom_type` is not null. (I can have a go at this when I have some time)

**Comment by danbjoseph** [comment]
I used the vertex tool to remove some of the roads and segments from the overpass query/export that I didn't want for the sample. Must have only deleted the vertices and not the feature itself. Interesting!

**Comment by danbjoseph** [comment]
If testing before a check for this is implemented, you can delete features with null geometry following: https://gis.stackexchange.com/a/276800

**Comment by ioalexei** [comment]
I've made a check to detect this and will make a pull request. 

```
if (gdf.geometry.isna()).any(): 
        raise ValueError("Input GeoDataFrame contains null geometries.")
```

But checking first - is it desireable to add an argument to `create_points` to optionally drop null geometries? Or is it better to just raise and error and let users fix the dataset before using it?

**Comment by danbjoseph** [comment]
I think it would be nice to have the raised error message and then have an option to deal with it inside the program (instead of having to go back to QGIS). What do you think?
Something like...
`Input GeoDataFrame contains null geometries. Rerun with --dropNull to drop these geometries.`

**Comment by danbjoseph** [comment]
it has. if you run `python -m src.create_points --help` it will include details on `--drop-null`
the `--help` command is mentioned in the readme, do you think we need to mention each flag in the readme or is mentioning how to get details through the help flag enough?
