### ISSUE TITLE
HIGHWAY_VALUES don't seem to be used to filter

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/street-view-green-view#36]
@jayqi would you be able to take a look at this?

i've modified and saved `create_points.py` to have the following:
```
HIGHWAY_VALUES = {
    "primary",
    "primary_link",
    "secondary",
    "secondary_link",
    "tertiary",
    "tertiary_link",
    "residential",
}
```
but when i run it, a `highway=tertiary` doesn't get points processed, whereas a `highway=service` does. this is not what i would expect. here is the file: [ParkView.geojson.zip](https://github.com/AmericanRedCross/street-view-green-view/files/15254059/ParkView.geojson.zip) and screenshots illustrating results are below.

a `highway=tertiary` with no points generated along its length:

<img width="825" alt="Screenshot 2024-05-08 at 3 45 34 PM" src="https://github.com/AmericanRedCross/street-view-green-view/assets/4806884/d0661620-a193-4569-994b-1cfda1f1f0c3">

a `highway=service` with points generated along its length:

<img width="732" alt="Screenshot 2024-05-08 at 3 45 54 PM" src="https://github.com/AmericanRedCross/street-view-green-view/assets/4806884/5a64be9f-91e1-4bae-bea4-2a2617c6b7d4">

**Comment by jayqi** [comment]
@danbjoseph First thing I would check is whether you have the package installed as editable. If you run in the command line:

```bash
pip freeze | grep street-view-green-view
```

Example output editable: 

```python
❯ pip freeze | grep street-view-green-view
-e git+https://github.com/AmericanRedCross/street-view-green-view.git@11006e81cb5d9e712b23240e0b2673d20ec79761#egg=src
```

Example output not editable:

```bash
❯ pip freeze | grep street-view-green-view
src @ file:///Users/jqi/repos/street-view-green-view
```

If it's not editable, then try reinstalling with `pip install -e .`

**Comment by danbjoseph** [comment]
appears to be editable?
```
(.venv) ➜  street-view-green-view git:(main) ✗ pip freeze | grep street-view-green-view
-e git+https://github.com/AmericanRedCross/street-view-green-view.git@037d04a4c9d70744943ce00ec29fd4c73650a980#egg=src
```

**Comment by danbjoseph** [comment]
yes, i think we should go with "include" - i think it would be easier to do only sidewalks and pedestrian paths or do roadways or whatever.
