### ISSUE TITLE
Configuration files for pipeline steps

### ISSUE THREAD

**Issue by jayqi** [AmericanRedCross/street-view-green-view#38]
There are various places where we may want to have more configurability. It would be useful to support configuration files. 

Examples:

- `create_points`
    - [X] Highway types to filter to
    - [X] Interpolation distance (`mini_dist`)
    - [X] drop null geometries 

see also #76, #77, and #78
    
(list updated by @danbjoseph on 26-Aug-2024)

**Comment by danbjoseph** [comment]
i think another configuration would be parameters for image selection like time of year or date range as mentioned in #39

**Comment by danbjoseph** [comment]
@jayqi completed the structure for the configuration file and an initial set of configurations. other items to be added to configuration list logged as individual issues.
