### ISSUE TITLE
protect main branch

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/street-view-green-view#6]
> **Your main branch isn't protected**
> Protect this branch from force pushing or deletion, or require status checks before merging. [View documentation.](https://docs.github.com/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/about-rulesets)

**Comment by danbjoseph** [comment]
@jayqi thank you for adding linting in #14 - i'd also be interested in any other project management best practices you think we should implement. related to this issue are there any repository settings we should adjust/enable?

**Comment by pekingPow** [comment]
Is this issue solved?
Did you try Branch Settings?

**Comment by danbjoseph** [comment]
there are a lot of branch settings options. it's a question of what the best settings are for this type of project at this stage. 
<img width="786" alt="Screenshot 2024-03-08 at 8 07 28 AM" src="https://github.com/AmericanRedCross/street-view-green-view/assets/4806884/6f8092f6-8ca9-4c17-8426-a420ddfcc243">

**Comment by dragonejt** [comment]
I think we definitely want to enable the first two, and possibly the third as well. That should serve our needs nicely. If we run into any issues we can just turn them back off later.

**Comment by danbjoseph** [comment]
done. thanks for the inputs!
