### ISSUE TITLE
progress assigning images to points different from downloaded number of images?

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/street-view-green-view#67]
the console log shows:
```
Assigning Images to Points:   2%|  | 17866/791462 [1:34:53<60:38:07,  3.54points/s]
```
but the folder on disc has less than 600 images in it?

is that expected? (the large difference between 17866 and <600)

**Comment by 6ug6unny** [comment]
The console log shows the number of points and not the number of images, I guess. And the number of points can be greater than the number of images. The script you shared seems to be processing many points but only saving unique images when they are successfully retrieved and meet certain criteria.
Also, I noticed that the get_image_from_coordinates method is not yet been implemented so it might be the one deciding if an image is always found or saved for each point.

**Comment by danbjoseph** [comment]
@6ug6unny can you say more about what you mean by: 
> Also, I noticed that the get_image_from_coordinates method is not yet been implemented so it might be the one deciding if an image is always found or saved for each point.

Is there code that is unused?

**Comment by 6ug6unny** [comment]
I was referring to the _get_image_from_coordinates_ method in the _image_source.py_ file. It doesn't seem to be implemented yet.

**Comment by dragonejt** [comment]
Hello, ImageSource in `image_source.py` is an interface or, in Python, an AbstractBaseClass. The respective implementations are in `mapillary.py` and `local_images.py`

**Comment by danbjoseph** [comment]
thanks for exploring this, seems like expected behavior.
