### ISSUE TITLE
use Mapillary API to retrieve image for each point

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/street-view-green-view#7]
download 1 image for each point. if no image is available within 10 meters of the point, flag it somehow in the eventual ouput.

- For the MVP we want to focus on 360 images like [this one](https://www.mapillary.com/app/?pKey=918722629622842&lat=43.311544088213&lng=-73.651056490169&z=17&focus=photo). We are planning for our project partner to be using GoPro MAX cameras.
- If we are downloading all the images: 
   - check Mapillary API rate limits
   - consider some sort of check on hard drive space or perhaps a warning such as "you are about to download 68,276 images (estimated XX GB), do you wish to proceed?"
   - what else?

**Comment by danbjoseph** [comment]
@dragonejt as you look at incorporating this into the overall process, remember that the first step is to ingest a roads file and create a sample of points (e.g. every 20 meters). in this second step, in addition to fetching a single image for each point and saving the image to disk, we want to associate each file with each point (e.g. by adding a property to the point that stores the filename and any other useful metadata from Mapillary). we will want to somehow record if there is not an image available (e.g. within 10m or half of the [`DEFAULT_MINI_DISTANCE`](https://github.com/AmericanRedCross/street-view-green-view/blob/aef19085cf5c33994fcc936b54b6071e8999b31d/src/create_points.py#L18) that was used in step 1).

and later, instead of just finding the closest image, we will want to be able to pass filter(s) such as for `captured_at` (e.g. to limit to the season when trees are leafed out, or for images from only the current year) and for one or more `creator` (e.g. to limit to only images a particular project team has captured).

**Comment by dragonejt** [comment]
Yeah, I think a good next step would be to implement a data parser to parse the roads file .zip and get the list of points, specifically their longitudes and latitudes. I think during the image download process, it is possible to write a JSON file where the keys are the longitudes and latitudes and the values are the image file path or id, or an error if it wasn't able to download that image.
