### ISSUE TITLE
web map legend not generating correctly

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/street-view-green-view#88]
using this file:
[surabaya_segmentation_hex9.gpkg.zip](https://github.com/user-attachments/files/17515549/surabaya_segmentation_hex9.gpkg.zip)
legend is no good:
<img width="451" alt="Screenshot 2024-10-25 at 11 03 22 AM" src="https://github.com/user-attachments/assets/39d3b416-7363-470d-8b84-2d5969d33a8a">

(@ioalexei related to your work on web map generation)

**Comment by ioalexei** [comment]
I'll look into it!

**Comment by ioalexei** [comment]
Added a fix with https://github.com/AmericanRedCross/street-view-green-view/pull/46/commits/cb131f44b2e3c408dae64a3b5653a59f27a7e01c 

- changed int to float for legend generation, so that it handles smaller ranges
- changed rounding in the legend labels to 2 decimal places rather than 0

**Comment by danbjoseph** [comment]
thanks! looks good!
<img width="751" alt="Screenshot 2024-11-20 at 8 17 15 PM" src="https://github.com/user-attachments/assets/15d41706-8d2f-4e2d-8968-c4f10bd0642f">
