### ISSUE TITLE
(optional) process to do everything locally

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/street-view-green-view#9]
We can use the [mapillary_tools video processing](https://github.com/mapillary/mapillary_tools#video-processing) to sample images from 360 videos recorded by a GoPro MAX and save them locally with GPS coordinates. Can we then have a script that matches images from a local folder to the geo points (instead of searching and pulling from the Mapillary API)?

**Comment by dragonejt** [comment]
I'm trying to write a script that takes local images from a folder and then uses the EXIF location data (latitude and longitude) to match it with a point. However, the images that are downloaded from mapillary seem to have the EXIF data scrubbed, so I cannot test it with mapillary images. I'm going to find other images that might have EXIF data to test on, but do we know if the GoPro cameras that volunteers will be using captures EXIF data, or if there is a simpler way to do this?

**Comment by danbjoseph** [comment]
I think reading the EXIF data is the right choice. I'm guessing you'll want to do a nearest neighbor analysis, something like: https://autogis-site.readthedocs.io/en/2021/notebooks/L3/06_nearest-neighbor-faster.html

To be uploaded to Mapillary, images need EXIF location data. The cameras we will be using tag each image with the GPS coordinates. I will collect a sample image set this weekend and put it somewhere you can download!
